spring.application.name=discovery-service

# Port chay cho Eureka Dashboard
server.port=8761

# Khong tu dang ky ban than vao chinh no
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Tat can bao ve trong trang thai phat trien (De server khong check peer network)
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000
